apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
  namespace: nginx
spec:
  selector:
    app: nginx
  type: NodePort  # Exposes service on a node port
  ports:
    - protocol: TCP
      port: 80        # Cluster-internal service port
      targetPort: 80  # The port inside the pod
      nodePort: 30020 # Exposes it on this fixed port (range: 30000-32767)