apiVersion: v1
kind: Service
metadata:
  name: surrealdb-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: surrealdb
  ports:
    - name: web
      port: 8000
      targetPort: 8000
      nodePort: 30002  # You can choose any port between 30000-32767

