apiVersion: v1
kind: Service
metadata:
  name: surrealdb-tikv-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: surrealdb
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080 # You can choose any port in the range 30000-32767